### ISSUE TITLE
Homebridge crashed after configure the plugin

### ISSUE THREAD

**Issue by MikeDeltaHH** [kurtwarwick-new/homebridge-appletv-now-playing#30]
Hi there!

I do a fresh HB installation (1.1.1) with Homebridge Config UI X and your plugin - i configure the plugin and restart my homebridge and it crashed:

[7/15/2020, 9:36:09 PM] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
[7/15/2020, 9:36:14 PM] [HB Supervisor] Restarting Homebridge...
[7/15/2020, 9:36:14 PM] [HB Supervisor] Starting Homebridge with extra flags: -I
[7/15/2020, 9:36:14 PM] [HB Supervisor] Started Homebridge v1.1.1 with PID: 4771
[7/15/2020, 9:36:14 PM] Loaded config.json with 0 accessories and 2 platforms.
[7/15/2020, 9:36:14 PM] ---
[7/15/2020, 9:36:14 PM] Loaded plugin: homebridge-appletv-now-playing@0.3.6
[7/15/2020, 9:36:14 PM] Registering platform 'homebridge-appletv-now-playing.AppleTvNowPlayingPlatform'
[7/15/2020, 9:36:14 PM] ---
[7/15/2020, 9:36:15 PM] Loaded plugin: homebridge-config-ui-x@4.23.2
[7/15/2020, 9:36:15 PM] Registering platform 'homebridge-config-ui-x.config'
[7/15/2020, 9:36:15 PM] ---
[7/15/2020, 9:36:15 PM] Loading 2 platforms...
[7/15/2020, 9:36:15 PM] [Config] Initializing config platform...
[7/15/2020, 9:36:15 PM] [Config] Running in Service Mode
[7/15/2020, 9:36:15 PM] [AppleTvNowPlayingPlatform] Initializing AppleTvNowPlayingPlatform platform...
[7/15/2020, 9:36:15 PM] TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined
    at Function.from (buffer.js:331:9)
    at Function.parse (/usr/local/lib/node_modules/homebridge-appletv-now-playing/node_modules/node-appletv-x/dist/lib/credentials.js:21:49)
    at Object.parseCredentials (/usr/local/lib/node_modules/homebridge-appletv-now-playing/node_modules/node-appletv-x/dist/index.js:31:38)
    at /usr/local/lib/node_modules/homebridge-appletv-now-playing/src/platform.js:78:49
    at Array.map (<anonymous>)
    at Platform.cleanupAccessories (/usr/local/lib/node_modules/homebridge-appletv-now-playing/src/platform.js:77:65)
    at Platform.onApiDidFinishLaunching (/usr/local/lib/node_modules/homebridge-appletv-now-playing/src/platform.js:132:14)
    at HomebridgeAPI.emit (events.js:315:20)
    at HomebridgeAPI.signalFinished (/usr/local/lib/node_modules/homebridge/src/api.ts:251:10)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:160:14)
[7/15/2020, 9:36:15 PM] Got SIGTERM, shutting down Homebridge...

This is my plugin config:

 {
            "devices": [
                {
                    "name": "Apple TV",
                    "credentials": "XXX",
                    "inputs": [
                        {
                            "name": "Apple TV",
                            "index": 1,
                            "applicationId": "com.apple.tv"
                        },
                        {
                            "name": "Netflix",
                            "index": 13,
                            "applicationId": "com.netflix.Netflix"
                        },
                        {
                            "name": "MrMC",
                            "index": 17,
                            "applicationId": "tv.mrmc.mrmc.tvos"
                        }
                    ]
                }
            ],
            "platform": "AppleTvNowPlayingPlatform"
        }

Can you help?

Regards!
Mike

**Comment by MikeDeltaHH** [comment]
My mistake... wrong credentials...
