### ISSUE TITLE
TypeError: Cannot read property 'forEach' of undefined

### ISSUE THREAD

**Issue by mfw2010** [kurtwarwick-new/homebridge-appletv-now-playing#4]
I am excited to get this working. However after adding the config I get this error 

`TypeError: Cannot read property 'forEach' of undefined
    at HomebridgeAPI.unregisterPlatformAccessories (/usr/local/lib/node_modules/homebridge/src/api.ts:324:17)
    at Device.configureAccessory (/usr/local/lib/node_modules/homebridge-appletv-now-playing/src/device.js:25:23)
    at new Device (/usr/local/lib/node_modules/homebridge-appletv-now-playing/src/device.js:129:8)
    at Platform.onDeviceConnected (/usr/local/lib/node_modules/homebridge-appletv-now-playing/src/platform.js:90:23)
    at /usr/local/lib/node_modules/homebridge-appletv-now-playing/src/platform.js:86:60
TypeError: Cannot read property 'forEach' of undefined
    at HomebridgeAPI.unregisterPlatformAccessories (/usr/local/lib/node_modules/homebridge/src/api.ts:324:17)
    at Device.configureAccessory (/usr/local/lib/node_modules/homebridge-appletv-now-playing/src/device.js:25:23)
    at new Device (/usr/local/lib/node_modules/homebridge-appletv-now-playing/src/device.js:129:8)
    at Platform.onDeviceConnected (/usr/local/lib/node_modules/homebridge-appletv-now-playing/src/platform.js:90:23)
    at /usr/local/lib/node_modules/homebridge-appletv-now-playing/src/platform.js:86:60`

Any suggestions how I can resolve this?

**Comment by kurtwarwick-new** [comment]
Hi @mfw2010 

I do apologise for the delayed response! Given the global circumstances, hopefully you can understand.

Could you perhaps send me your configuration? I would like to ensure that all looks good. Please remember to hash out your credentials.

Regards

Kurt

**Comment by kurtwarwick-new** [comment]
Another question; had you perhaps tried the plugin using a previously obtained credentials with no success before getting this error?

Thanks.

K

**Comment by NainRouge** [comment]
Hey there --  I tried the previous version of this as well and I'm also getting the error.  I can't try with previously obtained creds since I'm installing this for the first time.

Here's my config:

{
            "platform": "AppleTvNowPlayingPlatform",
            "devices": [
                {
                    "name": "Da Apple TV",
                    "credentials": "B794AF12-C7A1-4472-86F3...."
                }
            ]
        },

**Comment by kurtwarwick-new** [comment]
Hi @NainRouge 

Thanks for your feedback, and for your configuration.

I'll have a look into this as soon as possible.

Regards.

Kurt

**Comment by kurtwarwick-new** [comment]
Hi

Please could you try out the new version? This issue should now be resolved.

Regards

Kurt

**Comment by NainRouge** [comment]
Have you incremented the version?  I don't see a new one available via NPM.

**Comment by NainRouge** [comment]
Still not seeing a new version available.

**Comment by kurtwarwick-new** [comment]
Hi @NainRouge 

I totally forgot to publish it to NPM.  I have done so now. It should reflect the latest changes.

Please let me know how it goes.

Kurt

**Comment by NainRouge** [comment]
Registers now. Thanks.
